// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VehicleAPI.Entities;

public partial class Driver
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public virtual ICollection<MotorVehicleDriver> MotorVehicleDriver { get; set; } = new List<MotorVehicleDriver>();
}