// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VehicleAPI.Entities;

public partial class InsurancePolicy
{
    public int Id { get; set; }

    public string PolicyProvider { get; set; }

    public virtual MotorVehicle MotorVehicle { get; set; }
}