// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VehicleAPI.Entities;

public partial class MotorVehicleDriver
{
    public int Id { get; set; }

    public int MotorVehicleId { get; set; }

    public int DriverId { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual MotorVehicle MotorVehicle { get; set; }
}