// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VehicleAPI.Entities;

public partial class MotorVehicle
{
    public int Id { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public int MotorVehicleTypeId { get; set; }

    public int InsurancePolicyId { get; set; }

    public virtual InsurancePolicy InsurancePolicy { get; set; }

    public virtual ICollection<MotorVehicleDriver> MotorVehicleDriver { get; set; } = new List<MotorVehicleDriver>();

    public virtual MotorVehicleType MotorVehicleType { get; set; }
}