// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VehicleAPI.Entities;

public partial class MotorVehicleType
{
    public int Id { get; set; }

    public string Type { get; set; }

    public virtual ICollection<MotorVehicle> MotorVehicle { get; set; } = new List<MotorVehicle>();
}